<?php
/**
 * Created by PhpStorm.
 * User: matheuslucio
 * Date: 25/10/15
 * Time: 08:54
 */
?>
<!-- begin PAGE TITLE AREA -->
<!-- Use this section for each page's title and breadcrumb layout. In this example a date range picker is included within the breadcrumb. -->
<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Cantores
                <small>Editar</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-users"></i> Cantores</li>
            </ol>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- end PAGE TITLE AREA -->

<div class="row">
    <!-- Horizontal Form Example -->
    <div class="col-lg-12">
        <?php
        if ($this->mensagem != null)
        {
            echo '<div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><strong>Atenção!</strong> ' . $this->mensagem . '</div>';
        }
        ?>
        <a href="/cantores" class="btn btn-default btn-square">Listar Cantores</a>
        <br />
        <br />
        <div class="portlet portlet-green">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h4>Edição de Cantor</h4>
                </div>
                <div class="portlet-widgets">
                    <a data-toggle="collapse" data-parent="#accordion" href="#horizontalFormExample"><i class="fa fa-chevron-down"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="horizontalFormExample" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <form class="form-horizontal" role="form" method="POST" name="upload-form" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Nome</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="nome_cantor" name="nome_cantor" placeholder="Nome" required="required" value="<?php echo utf8_encode($this->cantor->getNomeCantor()); ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Descrição</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="descricao_cantor" name="descricao_cantor" placeholder="Descrição" required="required" value="<?php echo utf8_encode($this->cantor->getDescricaoCantor()); ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Foto</label>
                            <div class="col-sm-10">
                                <input type="file" id="foto_cantor" name="foto_cantor">
                                <br />
                                Antiga:<br /><br />
                                <img src="<?php echo $this->cantor->getFotoCantor(); ?>" style="max-width: 400px">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default btn-square">Atualizar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    <!-- /.col-lg-12 (nested) -->
    <!-- End Horizontal Form Example -->
</div>