<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CmsUsuario extends \Application\Entity\CmsUsuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrId', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrLogEntrada', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrNome', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrLogin', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrSenha', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrPin', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrHabbo', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrEmail', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrStatus', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrIprever');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrId', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrLogEntrada', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrNome', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrLogin', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrSenha', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrPin', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrHabbo', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrEmail', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrStatus', '' . "\0" . 'Application\\Entity\\CmsUsuario' . "\0" . 'usrIprever');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CmsUsuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUsrId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getUsrId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsrId', array());

        return parent::getUsrId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsrLogEntrada($usrLogEntrada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsrLogEntrada', array($usrLogEntrada));

        return parent::setUsrLogEntrada($usrLogEntrada);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsrLogEntrada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsrLogEntrada', array());

        return parent::getUsrLogEntrada();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsrNome($usrNome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsrNome', array($usrNome));

        return parent::setUsrNome($usrNome);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsrNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsrNome', array());

        return parent::getUsrNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsrLogin($usrLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsrLogin', array($usrLogin));

        return parent::setUsrLogin($usrLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsrLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsrLogin', array());

        return parent::getUsrLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsrSenha($usrSenha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsrSenha', array($usrSenha));

        return parent::setUsrSenha($usrSenha);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsrSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsrSenha', array());

        return parent::getUsrSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsrPin($usrPin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsrPin', array($usrPin));

        return parent::setUsrPin($usrPin);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsrPin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsrPin', array());

        return parent::getUsrPin();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsrHabbo($usrHabbo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsrHabbo', array($usrHabbo));

        return parent::setUsrHabbo($usrHabbo);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsrHabbo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsrHabbo', array());

        return parent::getUsrHabbo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsrEmail($usrEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsrEmail', array($usrEmail));

        return parent::setUsrEmail($usrEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsrEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsrEmail', array());

        return parent::getUsrEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsrStatus($usrStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsrStatus', array($usrStatus));

        return parent::setUsrStatus($usrStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsrStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsrStatus', array());

        return parent::getUsrStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsrIprever($usrIprever)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsrIprever', array($usrIprever));

        return parent::setUsrIprever($usrIprever);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsrIprever()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsrIprever', array());

        return parent::getUsrIprever();
    }

}
