<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TbProduto extends \Application\Entity\TbProduto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'idProduto', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'codCardapio', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'nome', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'img', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'descricao', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'resumo', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'valor', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'idCategoriaProduto');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'idProduto', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'codCardapio', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'nome', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'img', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'descricao', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'resumo', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'valor', '' . "\0" . 'Application\\Entity\\TbProduto' . "\0" . 'idCategoriaProduto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TbProduto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdProduto()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdProduto();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProduto', array());

        return parent::getIdProduto();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodCardapio($codCardapio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodCardapio', array($codCardapio));

        return parent::setCodCardapio($codCardapio);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodCardapio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodCardapio', array());

        return parent::getCodCardapio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setImg($img)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImg', array($img));

        return parent::setImg($img);
    }

    /**
     * {@inheritDoc}
     */
    public function getImg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImg', array());

        return parent::getImg();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', array($descricao));

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', array());

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setResumo($resumo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResumo', array($resumo));

        return parent::setResumo($resumo);
    }

    /**
     * {@inheritDoc}
     */
    public function getResumo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResumo', array());

        return parent::getResumo();
    }

    /**
     * {@inheritDoc}
     */
    public function setValor($valor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValor', array($valor));

        return parent::setValor($valor);
    }

    /**
     * {@inheritDoc}
     */
    public function getValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValor', array());

        return parent::getValor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCategoriaProduto(\Application\Entity\TbCategoriaProduto $idCategoriaProduto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCategoriaProduto', array($idCategoriaProduto));

        return parent::setIdCategoriaProduto($idCategoriaProduto);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCategoriaProduto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCategoriaProduto', array());

        return parent::getIdCategoriaProduto();
    }

}
