<?php
/**
 * Created by PhpStorm.
 * User: matheuslucio
 * Date: 25/10/15
 * Time: 08:54
 */
?>
<!-- begin PAGE TITLE AREA -->
<!-- Use this section for each page's title and breadcrumb layout. In this example a date range picker is included within the breadcrumb. -->
<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Produtos
                <small>Listar</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-cutlery"></i> Produtos</li>
            </ol>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- end PAGE TITLE AREA -->

<div class="row">
    <!-- Inline Form Example -->
    <!-- .col-lg-12 (open) -->
    <div class="col-lg-12">
        <div class="row">
            <div class="col-md-6">
                <a href="/produtos/cadastro" class="btn btn-green btn-square">Cadastrar Produto</a>
            </div>
            <div class="col-md-6">
                <div class="input-append bootstrap-timepicker input-group">
                    <span class="input-group-btn">
                        <button class="btn btn-default add-on" type="button">
                            Visualizando Categoria:
                        </button>
                    </span>
                    <select class="form-control" id="select-categoria" onchange="changeCategoria()">
                        <?php foreach ($this->categorias as $categoria) { ?>
                            <option value="<?php echo $categoria->getIdCategoria(); ?>"<?php if ($categoria->getIdCategoria() == $this->categoriaAtual->getIdCategoria()) {
                                echo ' selected';
                            } ?>>
                                <?php echo $categoria->getIdCategoria(); ?> - <?php echo $categoria->getNomeCategoria(); ?>
                            </option>
                        <?php } ?>
                    </select>
                </div>
            </div>
        </div>
        <br/>

        <div class="portlet portlet-default">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h4>Produtos</h4>
                </div>
                <div class="portlet-widgets">
                    <a data-toggle="collapse" data-parent="#accordion" href="#inlineFormExample"><i
                                class="fa fa-chevron-down"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="inlineFormExample" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <div class="table-responsive">
                        <table id="example-table" class="table table-striped table-bordered table-hover table-green">
                            <thead>
                            <tr>
                                <th>Foto</th>
                                <th>Código</th>
                                <th>Nome</th>
                                <th>Resumo</th>
                                <th>Preço</th>
                                <th>Ações</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($this->produtos as $produto) { ?>
                                <tr>
                                    <td><img src="<?php echo $produto->getImg(); ?>" width="100px"/></td>
                                    <td><?php echo $produto->getCodCardapio(); ?></td>
                                    <td><?php echo utf8_decode($produto->getNome()); ?></td>
                                    <td width="15%"><?php echo $produto->getResumo(); ?></td>
                                    <td width="10%">R$ <?php echo $produto->getValor(); ?></td>
                                    <td width="30%" class="tooltip-demo">
                                        <a href="/produtos/visualiza/<?php echo $produto->getIdProduto(); ?>"
                                           class="btn btn-purple btn-square" data-toggle="tooltip" data-placement="top"
                                           title="Visualizar"><i class="fa fa-search"></i> Visualizar</a>
                                        <a href="/produtos/edita/<?php echo $produto->getIdProduto(); ?>"
                                           class="btn btn-blue btn-square" data-toggle="tooltip" data-placement="top"
                                           title="Editar"><i class="fa fa-edit"></i> Editar</a>
                                        <a href="#delete" data-toggle="tooltip" data-placement="top" title="Deletar"
                                           class="delete_open btn btn-red btn-square"
                                           onclick="deletaProduto(<?php echo $produto->getIdProduto(); ?>, '<?php echo utf8_encode($produto->getNome()); ?>');"
                                           data-toggle="tooltip" data-placement="top" title="Deletar"><i
                                                class="fa fa-trash-o"></i> Deletar</a>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    <!-- /.col-lg-12 (nested) -->
    <!-- End Inline Form Example -->
</div>

<!-- Delete Notification Box -->
<div id="delete">
    <div class="logout-message">
        <br/>

        <h3>
            <i class="fa fa-trash-o text-green"></i> Deseja Apagar <b id="nome_cliente_apagar">--</b>?
        </h3>

        <p>Clique em "Sim" para apagar este produto.</p>
        <ul class="list-inline">
            <li>
                <a href="#" class="btn btn-green" id="url_cliente_apagar">
                    <strong>Sim</strong>
                </a>
            </li>
            <li>
                <button class="delete_close btn btn-green">Cancelar</button>
            </li>
        </ul>
    </div>
</div>
<!-- /#delete -->

<script>
    function deletaProduto(id, nome) {
        $('#nome_cliente_apagar').html(nome);
        $('#url_cliente_apagar').attr('href', '/produtos/deleta/' + id);
    }

    function changeCategoria() {
        location.href = '/produtos/mudar-categoria/' + $('#select-categoria').val();
    }
</script>