<?php
/**
 * Created by PhpStorm.
 * User: matheuslucio
 * Date: 25/10/15
 * Time: 08:54
 */
?>
<!-- begin PAGE TITLE AREA -->
<!-- Use this section for each page's title and breadcrumb layout. In this example a date range picker is included within the breadcrumb. -->
<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Usuários
                <small>Cadastrar</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-users"></i> Usuários</li>
            </ol>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- end PAGE TITLE AREA -->

<div class="row">
    <!-- Horizontal Form Example -->
    <div class="col-lg-12">
        <?php
        if ($this->mensagem != null)
        {
            echo '<div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><strong>Atenção!</strong> ' . $this->mensagem . '</div>';
        }
        ?>
        <a href="/usuarios" class="btn btn-default btn-square">Listar Usuários</a>
        <br />
        <br />
        <div class="portlet portlet-green">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h4>Cadastro de Usuário</h4>
                </div>
                <div class="portlet-widgets">
                    <a data-toggle="collapse" data-parent="#accordion" href="#horizontalFormExample"><i class="fa fa-chevron-down"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="horizontalFormExample" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <form class="form-horizontal" role="form" method="POST">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Nome</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="nome_usuario" name="nome_usuario" placeholder="Nome" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 control-label">E-mail</label>
                            <div class="col-sm-10">
                                <input type="email" class="form-control" id="email_usuario" name="email_usuario" placeholder="E-mail" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 control-label">Senha</label>
                            <div class="col-sm-10">
                                <input type="password" class="form-control" id="senha_usuario" name="senha_usuario" placeholder="Senha" required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default btn-square">Cadastrar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    <!-- /.col-lg-12 (nested) -->
    <!-- End Horizontal Form Example -->
</div>