<?php
/**
 * Created by PhpStorm.
 * User: matheuslucio
 * Date: 25/10/15
 * Time: 08:54
 */
?>
<!-- begin PAGE TITLE AREA -->
<!-- Use this section for each page's title and breadcrumb layout. In this example a date range picker is included within the breadcrumb. -->
<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Usuários
                <small>Listar</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-users"></i> Usuários</li>
            </ol>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- end PAGE TITLE AREA -->

<div class="row">
    <!-- Inline Form Example -->
    <!-- .col-lg-12 (open) -->
    <div class="col-lg-12">
        <a href="/usuarios/cadastro" class="btn btn-green btn-square">Cadastrar Usuário</a>
        <br/>
        <br/>

        <div class="portlet portlet-default">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h4>Usuários</h4>
                </div>
                <div class="portlet-widgets">
                    <a data-toggle="collapse" data-parent="#accordion" href="#inlineFormExample"><i
                            class="fa fa-chevron-down"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="inlineFormExample" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <div class="table-responsive">
                        <table id="example-table" class="table table-striped table-bordered table-hover table-green">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Nome</th>
                                <th>E-mail</th>
                                <th>Ações</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($this->usuarios as $usuario) { ?>
                                <tr>
                                    <td><?php echo $usuario->getUsrId(); ?></td>
                                    <td><?php echo $usuario->getUsrNome(); ?></td>
                                    <td><?php echo $usuario->getUsrEmail(); ?></td>
                                    <td width="20%" class="tooltip-demo">
                                        <a href="/usuarios/edita/<?php echo $usuario->getUsrId(); ?>"
                                           class="btn btn-blue btn-square" data-toggle="tooltip" data-placement="top"
                                           title="Editar"><i class="fa fa-edit"></i></a>
                                        <a href="#delete" data-toggle="tooltip" data-placement="top" title="Deletar"
                                           class="delete_open btn btn-red btn-square"
                                           onclick="deletaUsuario(<?php echo $usuario->getUsrId(); ?>, '<?php echo $usuario->getUsrNome(); ?>');"
                                           data-toggle="tooltip" data-placement="top" title="Deletar"><i
                                                class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    <!-- /.col-lg-12 (nested) -->
    <!-- End Inline Form Example -->
</div>

<!-- Delete Notification Box -->
<div id="delete">
    <div class="logout-message">
        <br/>

        <h3>
            <i class="fa fa-trash-o text-green"></i> Deseja Apagar <b id="nome_usuario_apagar">--</b>?
        </h3>

        <p>Clique em "Sim" para apagar este usuário.</p>
        <ul class="list-inline">
            <li>
                <a href="#" class="btn btn-green" id="url_usuario_apagar">
                    <strong>Sim</strong>
                </a>
            </li>
            <li>
                <button class="delete_close btn btn-green">Cancelar</button>
            </li>
        </ul>
    </div>
</div>
<!-- /#delete -->

<script>
    function deletaUsuario(id, nome) {
        $('#nome_usuario_apagar').html(nome);
        $('#url_usuario_apagar').attr('href', '/usuarios/deleta/' + id);
    }
</script>