<?php
/**
 * Created by PhpStorm.
 * User: matheuslucio
 * Date: 25/10/15
 * Time: 08:54
 */
?>
<!-- begin PAGE TITLE AREA -->
<!-- Use this section for each page's title and breadcrumb layout. In this example a date range picker is included within the breadcrumb. -->
<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Início
                <small>Página Inicial</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-dashboard"></i> Início</li>
            </ol>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- end PAGE TITLE AREA -->

<!-- begin DASHBOARD CIRCLE TILES -->
<div class="row">
    <div class="col-lg-4 col-sm-6">
        <div class="circle-tile">
            <a href="/cantores">
                <div class="circle-tile-heading dark-blue">
                    <i class="fa fa-microphone fa-fw fa-3x"></i>
                </div>
            </a>

            <div class="circle-tile-content dark-blue">
                <div class="circle-tile-description text-faded">
                    Cantores
                </div>
                <div class="circle-tile-number text-faded">
                    <?php echo $this->countCantores; ?>
                    <span id="sparklineA"></span>
                </div>
                <a href="/cantores" class="circle-tile-footer">Gerenciar <i class="fa fa-chevron-circle-right"></i></a>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-6">
        <div class="circle-tile">
            <a href="/cantores">
                <div class="circle-tile-heading green">
                    <i class="fa fa-calendar fa-fw fa-3x"></i>
                </div>
            </a>

            <div class="circle-tile-content green">
                <div class="circle-tile-description text-faded">
                    Dias
                </div>
                <div class="circle-tile-number text-faded">
                    <?php echo $this->countDias; ?>
                </div>
                <a href="/cantores" class="circle-tile-footer">Gerenciar <i class="fa fa-chevron-circle-right"></i></a>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-6">
        <div class="circle-tile">
            <a href="/produtos">
                <div class="circle-tile-heading orange">
                    <i class="fa fa-cutlery fa-fw fa-3x"></i>
                </div>
            </a>

            <div class="circle-tile-content orange">
                <div class="circle-tile-description text-faded">
                    Produtos
                </div>
                <div class="circle-tile-number text-faded">
                    <?php echo $this->countProdutos; ?>
                </div>
                <a href="/produtos" class="circle-tile-footer">Gerenciar <i class="fa fa-chevron-circle-right"></i></a>
            </div>
        </div>
    </div>
</div>
<!-- end DASHBOARD CIRCLE TILES -->

<div class="row">
    <!-- Inline Form Example -->
    <!-- .col-lg-12 (open) -->
    <div class="col-lg-12">
        <div class="portlet portlet-green">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h4>Seja bem vindo!</h4>
                </div>
                <div class="portlet-widgets">
                    <a data-toggle="collapse" data-parent="#accordion" href="#inlineFormExample"><i
                            class="fa fa-chevron-down"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="inlineFormExample" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <p>Esse sistema foi criado para gerenciar a agenda e os produtos do cardápio virtual - Paraíba Carne de Sol.</p>
                </div>
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    <!-- /.col-lg-12 (nested) -->
    <!-- End Inline Form Example -->
</div>