<?php
/**
 * Created by PhpStorm.
 * User: matheuslucio
 * Date: 25/10/15
 * Time: 08:54
 */
?>
<!-- begin PAGE TITLE AREA -->
<!-- Use this section for each page's title and breadcrumb layout. In this example a date range picker is included within the breadcrumb. -->
<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Fotos
                <small>Listar</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-users"></i> Fotos</li>
            </ol>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<!-- end PAGE TITLE AREA -->

<div class="row">
    <!-- Inline Form Example -->
    <!-- .col-lg-12 (open) -->
    <div class="col-lg-12">
        <a href="/fotos" class="btn btn-green btn-square">Listar Fotos</a>
        <br/>
        <br/>

        <div class="portlet portlet-default">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h4>Fotos</h4>
                </div>
                <div class="portlet-widgets">
                    <a data-toggle="collapse" data-parent="#accordion" href="#inlineFormExample"><i
                            class="fa fa-chevron-down"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div id="inlineFormExample" class="panel-collapse collapse in">
                <div class="portlet-body">
                    <div class="table-responsive">
                        <table id="example-table" class="table table-striped table-bordered table-hover table-green">
                            <thead>
                            <tr>
                                <th>Foto</th>
                                <th>Exibindo no Site</th>
                                <th>Ações</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($this->fotos as $foto) { ?>
                                <tr>
                                    <td><a href="<?php echo $foto->getSrc(); ?>" target="_blank"><img
                                                src="<?php echo $foto->getThumb(); ?>"/></a></td>
                                    <td><?php if ($foto->getExibe() == 'sim') { ?>Sim<?php } else { ?>Não<?php } ?></td>
                                    <td width="20%" class="tooltip-demo">
                                        <?php if ($foto->getExibe() == 'sim') { ?>
                                            <a href="/fotos/desativar/<?php echo $foto->getId(); ?>"
                                               class="btn btn-danger btn-square" data-toggle="tooltip"
                                               data-placement="top"
                                               title="Desativar"><i class="fa fa-power-off"></i> Desativar</a>
                                        <?php } else { ?>
                                            <a href="/fotos/ativar/<?php echo $foto->getId(); ?>"
                                               class="btn btn-success btn-square" data-toggle="tooltip"
                                               data-placement="top"
                                               title="Ativar"><i class="fa fa-power-off"></i> Ativar</a>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    <!-- /.col-lg-12 (nested) -->
    <!-- End Inline Form Example -->
</div>

<!-- Delete Notification Box -->
<div id="delete">
    <div class="logout-message">
        <br/>

        <h3>
            <i class="fa fa-trash-o text-green"></i> Deseja Apagar <b id="nome_cliente_apagar">--</b>?
        </h3>

        <p>Clique em "Sim" para apagar este cliente.</p>
        <ul class="list-inline">
            <li>
                <a href="#" class="btn btn-green" id="url_cliente_apagar">
                    <strong>Sim</strong>
                </a>
            </li>
            <li>
                <button class="delete_close btn btn-green">Cancelar</button>
            </li>
        </ul>
    </div>
</div>
<!-- /#delete -->

<script>
    function deletaCliente(id, nome) {
        $('#nome_cliente_apagar').html(nome);
        $('#url_cliente_apagar').attr('href', '/clientes/deleta/' + id);
    }
</script>